package ev.laborai.pirmaslab.mybatis.dao;

import ev.laborai.pirmaslab.mybatis.model.Driver;
import java.util.List;

public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Tue Mar 08 08:18:42 EET 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Tue Mar 08 08:18:42 EET 2022
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Tue Mar 08 08:18:42 EET 2022
     */
    Driver selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Tue Mar 08 08:18:42 EET 2022
     */
    List<Driver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Tue Mar 08 08:18:42 EET 2022
     */
    int updateByPrimaryKey(Driver record);
}