package ev.laborai.pirmaslab.mybatis.dao;

import ev.laborai.pirmaslab.mybatis.model.Driver;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    Driver selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    List<Driver> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DRIVER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    int updateByPrimaryKey(Driver record);
}