package ev.laborai.pirmaslab.mybatis.dao;

import ev.laborai.pirmaslab.mybatis.model.Rider;
import java.util.List;

public interface RiderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RIDER
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RIDER
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    int insert(Rider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RIDER
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    Rider selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RIDER
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    List<Rider> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.RIDER
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    int updateByPrimaryKey(Rider record);
}