package ev.laborai.pirmaslab.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MAKE
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private String make;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.PLATENUMBER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private String platenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.DRIVER_ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private Long driverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MAKE
     *
     * @return the value of PUBLIC.CAR.MAKE
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public String getMake() {
        return make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MAKE
     *
     * @param make the value for PUBLIC.CAR.MAKE
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setMake(String make) {
        this.make = make;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MODEL
     *
     * @return the value of PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MODEL
     *
     * @param model the value for PUBLIC.CAR.MODEL
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.PLATENUMBER
     *
     * @return the value of PUBLIC.CAR.PLATENUMBER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public String getPlatenumber() {
        return platenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.PLATENUMBER
     *
     * @param platenumber the value for PUBLIC.CAR.PLATENUMBER
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setPlatenumber(String platenumber) {
        this.platenumber = platenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.DRIVER_ID
     *
     * @return the value of PUBLIC.CAR.DRIVER_ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public Long getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.DRIVER_ID
     *
     * @param driverId the value for PUBLIC.CAR.DRIVER_ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setDriverId(Long driverId) {
        this.driverId = driverId;
    }
}