package ev.laborai.pirmaslab.mybatis.model;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    private String surname;

    private float rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.ID
     *
     * @return the value of PUBLIC.DRIVER.ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.ID
     *
     * @param id the value for PUBLIC.DRIVER.ID
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.NAME
     *
     * @return the value of PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.NAME
     *
     * @param name the value for PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.SURNAME
     *
     * @return the value of PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.SURNAME
     *
     * @param surname the value for PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Mon Mar 14 12:55:58 EET 2022
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    public float getRating() {
        return rating;
    }

    public void setRating(float rating) {
        this.rating = rating;
    }

}