package ev.laborai.pirmaslab.mybatis.model;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.CARS_ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    private Long carsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.RIDERS_ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    private Long ridersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.ID
     *
     * @return the value of PUBLIC.DRIVER.ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.ID
     *
     * @param id the value for PUBLIC.DRIVER.ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.NAME
     *
     * @return the value of PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.NAME
     *
     * @param name the value for PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.SURNAME
     *
     * @return the value of PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.SURNAME
     *
     * @param surname the value for PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.CARS_ID
     *
     * @return the value of PUBLIC.DRIVER.CARS_ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public Long getCarsId() {
        return carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.CARS_ID
     *
     * @param carsId the value for PUBLIC.DRIVER.CARS_ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public void setCarsId(Long carsId) {
        this.carsId = carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.RIDERS_ID
     *
     * @return the value of PUBLIC.DRIVER.RIDERS_ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public Long getRidersId() {
        return ridersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.RIDERS_ID
     *
     * @param ridersId the value for PUBLIC.DRIVER.RIDERS_ID
     *
     * @mbg.generated Wed Mar 09 16:30:46 EET 2022
     */
    public void setRidersId(Long ridersId) {
        this.ridersId = ridersId;
    }
}